version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tornedalen-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tornedalen
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql-data:
